### ISSUE TITLE
Create a random number generator from 3000 to 40,000

### ISSUE THREAD

**Issue by zeroxnone** [zeroxnone/GridLock#2]
-Herbert Crooks

**Comment by Hcrooks** [comment]
import random # importing "random" for random operations

def RandomNumberGenerator_3000to40000(): #defining a function RandomNumberGenerator_3000to40000() for the task
    x=random.randrange(3000, 40001) # using randrange() to generate in range from 3000 to 40000, 40001 is used because last number is not included in the range elsewise
    return x #returning the value
    
x=RandomNumberGenerator_3000to40000() #calling the function and saving it in variable "x"
print("A random number from range 3000 to 40,000 is :", x) #printing the number stored in "x"
